import type { Drug } from "./types";

export const MOCK_DRUGS: Drug[] = [
  {
    id: "d1",
    brandName: "Dolo 650",
    salt: "Paracetamol",
    strength: "650mg",
    form: "Tablet",
    manufacturer: "Micro Labs Ltd",
  },
  {
    id: "d2",
    brandName: "Crocin Advance",
    salt: "Paracetamol",
    strength: "500mg",
    form: "Tablet",
    manufacturer: "GlaxoSmithKline",
  },
  {
    id: "d3",
    brandName: "Augmentin 625 Duo",
    salt: "Amoxycillin + Clavulanic Acid",
    strength: "500mg + 125mg",
    form: "Tablet",
    manufacturer: "GlaxoSmithKline",
  },
  {
    id: "d4",
    brandName: "Glycomet-GP 1",
    salt: "Metformin + Glimepiride",
    strength: "500mg + 1mg",
    form: "Tablet",
    manufacturer: "USV Ltd",
  },
  {
    id: "d5",
    brandName: "Pan 40",
    salt: "Pantoprazole",
    strength: "40mg",
    form: "Tablet",
    manufacturer: "Alkem Laboratories",
  },
  {
    id: "d6",
    brandName: "Thyronorm",
    salt: "Thyroxine Sodium",
    strength: "100mcg",
    form: "Tablet",
    manufacturer: "Abbott",
  },
  {
    id: "d7",
    brandName: "Shelcal 500",
    salt: "Calcium + Vitamin D3",
    strength: "500mg + 250IU",
    form: "Tablet",
    manufacturer: "Torrent Pharmaceuticals",
  },
  {
    id: "d8",
    brandName: "Becosules",
    salt: "B-Complex + Vitamin C",
    strength: "N/A",
    form: "Capsule",
    manufacturer: "Pfizer",
  },
  {
    id: "d9",
    brandName: "Ascoril LS",
    salt: "Levosalbutamol + Ambroxol + Guaiphenesin",
    strength: "1mg + 30mg + 50mg",
    form: "Syrup",
    manufacturer: "Glenmark Pharmaceuticals",
  },
  {
    id: "d10",
    brandName: "Telma 40",
    salt: "Telmisartan",
    strength: "40mg",
    form: "Tablet",
    manufacturer: "Glenmark Pharmaceuticals",
  },
];
